__author__ = "Chris Brannon <chris@the-brannons.com>"
__copyright__ = "See the file LICENSE for copyright and license info"
__license__ = "See the file LICENSE for copyright and license info"
__version__ = "0.3.2"
__maintainer__ = "Emmanuel Arias <eamanu@eamanu.com>"
__email__ = "chris@the-brannons.com, eamanu@eamanu.com"
